static const char black[] = "#1e2122";
static const char white[] = "#c7b89d";
static const char gray2[] = "#282b2c"; // unfocused window border
static const char gray3[] = "#5d6061";
static const char gray4[] = "#282b2c";
static const char blue[] = "#6f8faf"; // focused window border
static const char green[] = "#9fa540";
static const char red[] = "#ec6b64";
static const char yellow[] = "#d6b676";
static const char orange[] = "#ff7f2a";
static const char pink[] = "#cc7f94";
static const char col_borderbar[] = "#1e2122"; // inner border
